### ISSUE TITLE
guna2 UI AnimationType Names are Corrupted 

### ISSUE THREAD

**Issue by V01D-PH03N1X** [sobatdata/Test#2]
They are called like: 

G243B3E243A1636322A21201F2C3B30
G243B3E243A16362C2035281F2C3B30
G243B3E3A301636322A21201F2C3B30
G243B3E3A3016362C2035281F2C3B30
G243B3E2F300A3D2737

every animation Type has a name like that.

**Comment by sobatdata** [comment]
Hello, sorry for the inconvenience.



We've looked into it and will fix it soon.





----------------------

ATTENTION!!

Be careful with fake Guna.UI packages that are spread on nuget.

Please check the nuget profile first before installing from nuget manager.



Our nuget profile is: https://www.nuget.org/profiles/Sobatdata

----------------------



Thank You.



Kind regards,

GunaUI Team


Pada tanggal Rab, 4 Jan 2023 02.36, Sebastian Schindler <
***@***.***> menulis:

**Comment by V01D-PH03N1X** [comment]
Thanks for fix :)
